### PR TITLE
feat: remove hard requirement on imagick

### PR DESCRIPTION
**Pull request by kbond**
- Auto choose GD if imagick is not available
- Throws exception if neither are available

### CODE REVIEW

**Comment by francoism90** [comment]
https://github.com/spatie/image/blob/4f84e8618dddd017409110ac3ebd779c6645626c/src/Image.php#L53

**Comment by kbond** [comment]
Yep, I was just thinking if your environment has GD but not Imagick, it would be nice to auto-fallback to GD instead of an exception.

**Comment by freekmurze** [comment]
I'm going to hold off this one for now. I think this might be a bit confusing for people who think they have Imagick installed (but they don't) and are surprised GD is used (which has subtle differences compared to Imagick).

I might change my mind on this later.

**Comment by kbond** [comment]
Totally understand, thanks for considering!

**Comment by ariaieboy** [comment]
@freekmurze Unfortunately the imagick is not compatible with PHP 8.3 yet and because of that we can't upgrade our project to PHP 8.3

**Comment by francoism90** [comment]
This is a Spatie problem because?

**Comment by ariaieboy** [comment]
Since spatie/image required both GD and Imagick extension to be installed the composer throw error since we can't install imagick with PHP 8.3

**Comment by francoism90** [comment]
Yeah, but it's something they should fix upstream.

I don't understand why, but it seems to be fixed already, just needs a new release.

For now, you cannot upgrade to 8.3, unless you build the extension yourself.

**Comment by ariaieboy** [comment]
I think hard require both imagick and gd is not a good approach. what if I just want to use GD and ignore imagick?
even in V2 this extensions are not in package requirement:
https://github.com/spatie/image/blob/v2/composer.json
Since we support multiple drivers its up to users to install the required driver extensions and set it in the config file.

**Comment by francoism90** [comment]
A sorry, now I know what you want to do.

Yeah, they could move it to dev, so it's not required.

You can choose a driver already, see my previous comment.

**Comment by parallels999** [comment]
Also, if you use `GD`_(no plan to use imagick)_ add this to your `composer.json` on `config`
```json
"config": {
        "platform":{   
            "ext-imagick": "3.7.0"
        },
```

**Comment by freekmurze** [comment]
Reading config files feels a bit out of scope for this package, but if you whip up a PR I'll take a look.

**Pull request closed without merging**
