### PR TITLE
Bump league/glide to 2.0

### PR DESCRIPTION
**Pull request by nlemoine**

### CODE REVIEW

**Comment by NKDM44** [comment]
Not so nice...

{
    "message": "Class 'League\\Glide\\ServerFactory' not found",
    "exception": "Error",
    "file": "/var/www/vendor/spatie/image/src/GlideConversion.php",
    "line": 130,
    "trace": [
        {
            "file": "/var/www/vendor/spatie/image/src/GlideConversion.php",
            "line": 80,
            "function": "createGlideServer",
            "class": "Spatie\\Image\\GlideConversion",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/spatie/image/src/Image.php",
            "line": 140,
            "function": "performManipulations",
            "class": "Spatie\\Image\\GlideConversion",
            "type": "->"
        },
        {

**Comment by Nielsvanpach** [comment]
Thanks for letting us know. I'll look into it.

**Comment by nlemoine** [comment]
Works fine for me and tests pass. The `NotFound` class exists: https://github.com/thephpleague/glide/blob/2.0.0/src/ServerFactory.php

@NKDM44 Could you provide your dependencies?

**Comment by NKDM44** [comment]
Hello,

 

I am using imagick as image driver in a Docker environment. I had trouble with gd… 

 



 

Beste regards

NK

Von: Nico [mailto:notifications@github.com] 
Gesendet: Mittwoch, 10. März 2021 17:22
An: spatie/image
Cc: NKDM44; Mention
Betreff: Re: [spatie/image] Bump league/glide to 2.0 (#123)

 

Works fine for me and tests pass. The NotFound class exists: https://github.com/thephpleague/glide/blob/2.0.0/src/ServerFactory.php

@NKDM44 <https://github.com/NKDM44>  Could you provide your dependencies?

**Comment by nlemoine** [comment]
@Nielsvanpach Can you give this PR a second thought? The "class not found" error mentioned earlier in this topic doesn't seem to be related to the `league/glide` upgrade.

I'm using 1.10.3 on production sites and had no trouble with it.

**Comment by la5942** [comment]
Since this was reverted, is there any chance we can get this issue and PR reopened for testing? (I can open a new issue and PR if you would prefer)

**Comment by nlemoine** [comment]
Just realized `spatie/laravel-medialibrary` is using `league/flysystem:^1.0.64`. One of the main changes in `league/glide:^2.0` is that they migrated to `league/flysystem:^2.0`. 

I don't really get how some users ended up with those errors (#127 and spatie/laravel-medialibrary#2326) because composer should have either triggered a conflict (if explicitly requiring `spatie/image:^1.10.3`) or selected the `spatie/image` version (`<=1.10.2`) compatible with `league/flysystem:^1.0`. 

Try a `composer install` on this `composer.json` (>1.10.3 tags have been deleted for testing purposes):
```json
{
    "require": {
        "spatie/laravel-medialibrary": "^9.5"
    },
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/nlemoine/image.git"
        }
    ]
}
```
You will get `spatie/image:1.10.2` as expected.

Anyway, this confirms there's nothing wrong with this PR of this particular package.

**Comment by Nielsvanpach** [comment]
I'll look into releasing this in a new major

**Comment by nlemoine** [comment]
Thanks!

**Comment by Nielsvanpach** [comment]
Released as v2

**Pull request merged**
