### PR TITLE
#84 - Duplicate images test

### PR DESCRIPTION
**Pull request by nlemoine**
Hi @freekmurze 

Here's the unit test case. Let me know if I can help.

### CODE REVIEW

**Comment by freekmurze** [comment]
Why are you expecting the files to be the same size? You're working with two images that have a different size.

**Comment by nlemoine** [comment]
I'm not expecting the files to have the same size. I'm expecting the opposite:
```
$this->assertTrue(filesize($output_files[0]) !== filesize($output_files[1]));
```
Will return true if files don't have the same size but the test fails, meaning those files are the same. 

I pushed a clearer test that fails too.

**Comment by freekmurze** [comment]
Ok, we'll look into this, thanks for the test! 👍

**Comment by freekmurze** [comment]
This has been fixed in the latests version. We've also added a test.

Thank you for your work on this though 👍

**Comment by nlemoine** [comment]
Thanks for the fix! 👍

**Pull request closed without merging**
