### PR TITLE
Don't use folders in cache path

### PR DESCRIPTION
**Pull request by Synchro**
This is a fix for [#132 in spatie/browsershot](https://github.com/spatie/browsershot/issues/132)

### CODE REVIEW

**Comment by freekmurze** [comment]
Unsure about this. I kinda like the temp files being created in the `temp` directory of the system. When something goes wrong creating the image, your system will clean up the temp files. If temp files are created next to the image, and something goes wrong, you get some garbage files in your project.

**Comment by danhunsaker** [comment]
Near as I can work out, it still uses the temp folder as configured elsewhere, it just doesn't use a subfolder named the same as the temp image itself, which lets it avoid some issues on some platforms where you can't have a file and a folder with the same name.

**Comment by Synchro** [comment]
@danhunsaker yes, that's what I think it's doing - it's certainly working that way for me. What systems allow folder and file with the same name at the same time? The other way to avoid the issue would be to make the cache dir *not* based on the source file path, or to add some kind of prefix, so if your source file is in `/tmp/file.png`, cache could be somewhere like `/tmp/glidecache/file.png/xxx`. My images start off in the system temp dir - images are generated,  delivered, and then thrown away - but I don't think that's an unusual approach.

**Comment by Synchro** [comment]
BTW the style failure seems to be in master, not my fork.

**Comment by danhunsaker** [comment]
Linux generally doesn't mind, which is why that's the current behavior. I'm not certain what macOS allows. Mostly depends on the filesystem itself, though, rather than the OS alone.

**Comment by Synchro** [comment]
Really? This is on linux with ext4:

```
ubuntu@server:~$ touch x
ubuntu@server:~$ mkdir x
mkdir: cannot create directory ‘x’: File exists
```

**Comment by danhunsaker** [comment]
Huh. Must have misremembered that bit, then.

**Comment by freekmurze** [comment]
Thank you for this. I'll give it a shot, pull it in and tag a new version.

Might reverse this if users start to complain.

**Comment by Synchro** [comment]
Thanks. I think it should work for most - the fundamental issue is the assumption that the cache and source image should be in the same place, and from what I can gather (there's so much abstraction it's hard to figure out what's going on!), this happens inside glide.

**Pull request merged**
