### PR TITLE
let Fit::Max behave as described in the documentation

### PR DESCRIPTION
**Pull request by RaBic**
$image->fit(Fit::Max... should behave as described in the documentation. This is especially a problem in Mailcoach...

### CODE REVIEW

**Comment by RaBic** [comment]
See issue in laravel-mailcoach [here](https://github.com/spatie/laravel-mailcoach/issues/1542#issue-2134240748) and [here](https://github.com/spatie/laravel-mailcoach/issues/1535#issue-2120000747)

**Comment by freekmurze** [comment]
@timvandijck could you take a look?

**Comment by JapSeyz** [comment]
Any way to expedite the look? It has effectively broken our entire Mailcoach setup, as we can no longer upload images to the newsletters.

**Comment by timvandijck** [comment]
@RaBic this looks good, thank you for your help 👏

Release 3.3.7 with this fix should be up in a few moments.

**Pull request merged**
