### PR TITLE
add Avif Support

### PR DESCRIPTION
**Pull request by ariaieboy**

### CODE REVIEW

**Comment by freekmurze** [comment]
Nice, thank you!

**Comment by ariaieboy** [comment]
> Nice, thank you!

that was fast 👌

**Comment by freekmurze** [comment]
Your PR was perfect, in those cases we can move fast!

**Comment by mabdullahsari** [comment]
Keep up the good work, @ariaieboy! 💪

I have bookmarked this small but impactful PR as a "model PR" that shows what a quality PR should look like and contain. 

Thanks! 🙏

**Pull request merged**
