### PR TITLE
Add is_writeable check before deleting a directory

### PR DESCRIPTION
**Pull request by brendt**
Addresses #38

### CODE REVIEW

**Comment by brendt** [comment]
@Gummibeer you mentioned that this fix doesn't solve the underlying problem. Could you give some more context?

**Comment by Gummibeer** [comment]
@brendt my answer was just related to my issue, which wasn't the `/tmp` directory used by glide but the medialibrary temp directory - so the exception mentioned a lot of times in https://github.com/spatie/laravel-medialibrary/issues/887 should be solved here.
Even if I don't like the strategy to delete the whole directory, even if it's empty, cause the directory is, in every time, the php tmp directory `sys_get_temp_dir()`, delete the whole directory isn't the job of this package and could also produce other problems.

**Comment by taliptako** [comment]
@brendt You cant just delete /tmp even if its writable because of some reason.
[https://www.tldp.org/LDP/Linux-Filesystem-Hierarchy/html/tmp.html](https://www.tldp.org/LDP/Linux-Filesystem-Hierarchy/html/tmp.html)

**Comment by Gummibeer** [comment]
Good Link, that's what I meant. In addition to it: why do you want to delete the directory? This package doesn't create it. So even if it's not `tmp` it's a directory you don't know what it's for.

**Comment by brendt** [comment]
> You cant just delete /tmp even if its writable because of some reason.

That's a fair point. I looked further into why `$conversionResultDirectory` is `/tmp` in the first place. My understanding is that it should be `/tmp/<conversion directory>`. 

Is anyone able to reproduce the steps required to get plain `/tmp` as the path?

Another "fix" I could add is the following

```php
if ($conversionResultDirectory !== sys_get_temp_dir()) {}
```

But that's also still a monkey patch, I'd rather see the plain `/tmp` never appear again, though I'm unable to pinpoint why it happens at this moment.

**Comment by Gummibeer** [comment]
@brendt if you want to have another directory you have to add it to the full path.
https://github.com/spatie/image/blob/088540509d8a6c4c2fe786aeb84c8bce3872acc5/src/GlideConversion.php#L50-L53

And everything else you add there depends on the glide configuration itself - this is what `makeImage` returns:
https://github.com/thephpleague/glide/blob/8077f529a07ded3eed6c5dcf7f688249b626ddf3/src/Server.php#L263-L290
So to be save I would suggest to add any new directory there and it's fine.

**Comment by taliptako** [comment]
Can you merge it at least until you find the problem why its trying to delete /tmp directory.

**Comment by brendt** [comment]
@ammonkc found the problem: https://github.com/spatie/image/issues/38#issuecomment-381296285

We'll be looking at a permanent solution tomorrow.

**Pull request merged**
