### PR TITLE
WIP: add watermark manipulations

### PR DESCRIPTION
**Pull request by ariaieboy**
As mentioned in this issue https://github.com/spatie/laravel-medialibrary/issues/3459 and here https://github.com/spatie/laravel-medialibrary/issues/3459#issuecomment-1861610062 
there are some missing features in spatie/image V3 for watermarks.

including the ability to set padding and the size of the watermark based on the base image size using the `Percent` unit.

In this draft PR, I tried to add a method called `insertPadding` that tries to replicate the `watermarkPadding` functionality.

It's not the best code that I wrote but it works. 

In V2 we have a manipulation sequence that we can push any manipulations that we want into it. including the watermark manipulations. 

Since we don't have such functionality here Users must call the `insertPadding` method before calling the `insert` method.

If this impletention is good enough I can add https://spatie.be/docs/image/v2/image-manipulations/watermarks#content-watermark-size and https://spatie.be/docs/image/v2/image-manipulations/watermarks#content-watermark-fit-resize to V3 like the `insertPadding`.

@freekmurze @timvandijck

### CODE REVIEW

**Comment by freekmurze** [comment]
Great work here! 👍 

Instead of having to use separate `insertPadding` and `insert` method, I'd rather have one `watermark` method that takes parameters: `$otherImage, $paddingX, $paddingY, $paddingUnit, $alpha)`.

That's I think a bit more intuitive from a user perspective.

**Comment by ariaieboy** [comment]
> Great work here! 👍
> 
> Instead of having to use separate `insertPadding` and `insert` method, I'd rather have one `watermark` method that takes parameters: `$otherImage, $paddingX, $paddingY, $paddingUnit, $alpha)`.
> 
> That's I think a bit more intuitive from a user perspective.

The problem is that padding is not the only feature that we need to implement.
There is `watermarkHeight`, `watermarkWidth` and `watermarkFit`. according to the V2 doc:
https://spatie.be/docs/image/v1/image-manipulations/watermarks#content-watermark-fit-resize

that increases the watermark method params to 10.
`$otherImage, $paddingX, $paddingY, $paddingUnit, $width, $widthUnit, $height, $heightUnit,$fit, $alpha`

**Comment by ariaieboy** [comment]
We can combine the Units and the values in some sort of DTO, it will reduce the method parameter count to 6 but technically that's still 10 individual parameter.

**Comment by ariaieboy** [comment]
@freekmurze I added `watermark` method in this PR:
https://github.com/spatie/image/pull/219
Can you check it?

**Pull request closed without merging**
